### PR TITLE
Fix findbuyers and findprops to match by substring + allow whitespace for price range input 

### LINKED ISSUE #115: Allow whitespace when specifying price range
Currently, when specifying price range (e.g. `200 - 500`), extra whitespace is only allowed at start and end (e.g. ` 200 - 500` or `200 - 500 `).

For more flexibility, change regex in `PriceRange` class to allow for extra whitespaces between the range and the hyphen (e.g. `200    - 500` and `200 -    500`)

### LINKED ISSUE #169: [PE-D][Tester A] findbuyer does not work when search keyword is not a full word in Name
I expected `findbuyer -k` to perform partial matches because the UG suggests that it looks for buyers with the keyword "in their name". Below, I input the following command, expecting at least Bernice to show up:

But no results are given:

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Piyotato/ped#4

### LINKED ISSUE #172: [PE-D][Tester A] findprop does not work when search term is not full word in Property
I expected `findprop -k` to perform partial matches because the UG suggests that it looks for properties with the keyword "in their name". Below, I input the following command, expecting at least Tembusu to show up:

but instead got

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Piyotato/ped#5

### LINKED ISSUE #184: [PE-D][Tester D] Find feature not specific enough
Imagine having 1000 james and 1 james macconkey and 1000 other macconkeys. Hard to find james macconkey specifically.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: kynapy/ped#4

### LINKED ISSUE #186: [PE-D][Tester B] Feature - Find Doesn't Search for Sub-string
Multiple Properties with "test"  in the name

Only one property with the exact string returned

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: avock/ped#11

### PR DESCRIPTION
**Pull request by ChryslineLim**
Fixes #169
Fixes #184 
Fixes #186
Fixes #172 
Fixes #115

### CODE REVIEW

**Review by riccqi — APPROVED** [review]
LGTM! are you planning to update the UG for this command in another PR?

File: src/main/java/seedu/address/logic/commands/FindPropertiesCommand.java [hunk 1]
```diff
@@ -4,7 +4,7 @@
 
 import seedu.address.commons.core.Messages;
 import seedu.address.model.Model;
-import seedu.address.model.property.PropertyNameContainsKeywordsPredicate;
+import seedu.address.model.property.PropertyNameContainsSubstringPredicate;
 
 /**
  * Finds and lists all properties in property book whose name contains any of the argument keywords.
```
Comment (riccqi) [inline src/main/java/seedu/address/logic/commands/FindPropertiesCommand.java:10]: also, can update this haha
